image: maven:latest

variables:
  MAVEN_CLI_OPTS: '-s .m2/settings.xml --batch-mode --errors'
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  BUILD_FILE: "hello-1.0.0.jar"

cache:
  paths:
    - ./.m2/repository
    - target

stages:
  - test
  - sonar
  - build
  - deploy

before_script:
  - chmod +x mvnw

test:
  stage: test
  script:
    - ./mvnw test

sonar:
  stage: sonar
  script:
    - ./mvnw sonar:sonar -Dsonar.projectKey=hello -Dsonar.host.url=http://192.168.1.109:9000 -Dsonar.login=d44db619389c1fa07a2b39f42f94e88b370eacff

build:
  stage: build
  script:
    - ./mvnw package -DskipTests
  artifacts:
    paths:
    - target/${BUILD_FILE}

dev:
  stage: deploy
  script:
    - echo "Deploy to dev"
  only:
    - main
