image: maven:latest

variables:
  MAVEN_CLI_OPTS: '-s .m2/settings.xml --batch-mode --errors'
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  BUILD_FILE: "hello-1.0.0.jar"

cache:
  paths:
    - .m2/repository
    - target

stages:
  - test
  - build
  - deploy

before_script:
  - chmod +x mvnw

test:
  stage: test
  script:
    - ./mvnw test

build:
  stage: build
  script:
    - ./mvnw package -DskipTests
  artifacts:
    paths:
    - target/${BUILD_FILE}

dev:
  stage: deploy
  script:
    - echo "Deploy to dev"
  only:
    - main
